In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [3]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won
0,240.0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,...,31.6,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False
1,240.0,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,...,34.7,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True
2,240.0,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,...,31.7,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True
3,240.0,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,...,18.2,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False
4,240.0,240.0,38.0,76.0,0.500,7.0,21.0,0.333,25.0,30.0,...,33.3,43.9,147.0,119.0,BOS,100,1,2018,2017-10-18,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,240.0,42.0,96.0,0.438,15.0,42.0,0.357,10.0,21.0,...,63.5,29.7,115.0,127.0,LAL,81,0,2025,2025-04-13,True
20250,240.0,240.0,40.0,84.0,0.476,15.0,44.0,0.341,3.0,6.0,...,50.0,31.1,169.0,118.0,SAC,109,1,2025,2025-04-13,False
20251,240.0,240.0,46.0,88.0,0.523,14.0,34.0,0.412,3.0,3.0,...,30.0,34.7,135.0,128.0,PHO,98,0,2025,2025-04-13,True
20252,240.0,240.0,46.0,97.0,0.474,14.0,39.0,0.359,12.0,16.0,...,30.7,29.2,230.0,124.0,SAS,125,1,2025,2025-04-13,False
20253,240.0,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [4]:
df = df.sort_values("date")

In [5]:
df = df.reset_index(drop=True)

In [6]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won
0,240.0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,...,31.6,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False
1,240.0,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,...,34.7,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True
2,240.0,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,...,31.7,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True
3,240.0,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,...,18.2,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False
4,240.0,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,...,23.0,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,...,40.0,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False
20250,240.0,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,...,31.6,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True
20251,240.0,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,...,35.5,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False
20252,240.0,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,...,25.8,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True
20253,240.0,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [7]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [8]:
df = df.copy()
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team
df["target"] = df.groupby("team")["won"].shift(-1)

In [9]:
df["team"]

0        BOS
1        CLE
2        HOU
3        GSW
4        WAS
        ...
20249    CHO
20250    ATL
20251    ORL
20252    MEM
20253    SAS
Name: team, Length: 20254, dtype: object

In [10]:
df[df["team"]=="WAS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,True
33,240.0,40.0,75.0,0.533,6.0,17.0,0.353,29.0,35.0,0.829,...,43.6,215.0,122.0,DET,111,0,2018,2017-10-20,True,True
91,240.0,37.0,84.0,0.440,9.0,30.0,0.300,26.0,28.0,0.929,...,35.1,272.0,115.0,DEN,104,1,2018,2017-10-23,True,False
108,265.0,39.0,95.0,0.411,6.0,26.0,0.231,15.0,23.0,0.652,...,32.9,129.0,98.0,LAL,102,1,2018,2017-10-25,False,False
147,240.0,43.0,97.0,0.443,15.0,33.0,0.455,16.0,22.0,0.727,...,30.9,210.0,122.0,GSW,120,1,2018,2017-10-27,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20136,240.0,35.0,86.0,0.407,12.0,45.0,0.267,8.0,10.0,0.800,...,26.9,208.0,112.0,BOS,124,1,2025,2025-04-06,False,False
20161,240.0,38.0,91.0,0.418,11.0,39.0,0.282,11.0,15.0,0.733,...,26.6,145.0,112.0,IND,104,1,2025,2025-04-08,False,False
20165,240.0,34.0,87.0,0.391,10.0,33.0,0.303,25.0,30.0,0.833,...,31.5,165.0,109.0,PHI,122,0,2025,2025-04-09,False,False
20213,240.0,35.0,91.0,0.385,10.0,41.0,0.244,9.0,12.0,0.750,...,31.2,261.0,97.0,CHI,119,1,2025,2025-04-11,False,True
20237,240.0,46.0,90.0,0.511,16.0,37.0,0.432,11.0,17.0,0.647,...,33.1,162.0,125.0,MIA,118,1,2025,2025-04-13,True,NaN

In [11]:
df["target"][pd.isnull(df["target"])] = 2

C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [12]:
df["target"] = df["target"].astype(int, errors="ignore")

In [13]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True,1
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
20250,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
20251,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
20252,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
20253,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [14]:
df["won"].value_counts()

won
False    10127
True     10127
Name: count, dtype: int64

In [15]:
df["target"].value_counts()

target
0    10112
1    10112
2       30
Name: count, dtype: int64

In [16]:
nulls = pd.isnull(df)

In [17]:
nulls = nulls.sum()

In [18]:
nulls = nulls[nulls>0]

In [19]:
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [20]:
big_nulls = nulls[nulls==19530]

In [21]:
big_nulls

Series([], dtype: int64)

In [22]:
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [23]:
valid_columns = df.columns[~df.columns.isin(big_nulls.index)]

In [24]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'seasons', 'date', 'won', 'target'],
      dtype='object', length=152)

In [25]:
df = df[valid_columns].copy()

In [26]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True,1
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
20250,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
20251,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
20252,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
20253,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [27]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls>0]
nulls

ft%                 1
gmsc            20254
+/-             20254
mp_max          20254
mp_max.1        20254
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        20254
+/-_opp         20254
mp_max_opp      20254
mp_max_opp.1    20254
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [28]:
nulls = df.isnull().sum()
nulls = nulls[nulls > 0]

# 🔽 Put this next
cols_to_drop = nulls[nulls > 15].index
df.drop(columns=cols_to_drop, inplace=True)

In [29]:
nulls = df.isnull().sum()
nulls = nulls[nulls > 0]

In [30]:
cols_to_check = nulls.index.tolist()
df = df.dropna(subset=cols_to_check)

In [31]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls>0]
nulls

Series([], dtype: int64)

In [32]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,False,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,True,1
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,97.0,0.433,6.0,22.0,0.273,30.0,38.0,0.789,...,31.2,148.0,125.0,PHI,115,0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
20250,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
20251,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
20252,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
20253,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [33]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\tahsi\downloads\anaconda3\lib\site-packages (1.3.1)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\tahsi\downloads\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr=RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction = "forward", cv=split)

In [35]:
#columns we aren't going to scale
removed_columns = ["seasons", "date", "won", "target", "team", "team_opp"]

In [36]:
#columns we do scale
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [37]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns]=scaler.fit_transform(df[selected_columns])

C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\1350979795.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[selected_columns]=scaler.fit_transform(df[selected_columns])

In [38]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,seasons,date,won,target
0,0.0,0.340909,0.409836,0.333333,0.250000,0.366667,0.246819,0.418605,0.380952,0.719953,...,0.067949,0.194030,0.322581,CLE,0.321101,1.0,2018,2017-10-17,False,0
1,0.0,0.386364,0.327869,0.450000,0.142857,0.200000,0.217557,0.465116,0.380952,0.813302,...,0.101282,0.149254,0.376344,BOS,0.293578,0.0,2018,2017-10-17,True,1
2,0.0,0.590909,0.557377,0.514286,0.500000,0.516667,0.394402,0.279070,0.285714,0.631272,...,0.135897,0.751244,0.537634,GSW,0.495413,1.0,2018,2017-10-17,True,1
3,0.0,0.500000,0.278689,0.640476,0.535714,0.333333,0.606870,0.418605,0.317460,0.889148,...,0.117949,0.263682,0.526882,HOU,0.504587,0.0,2018,2017-10-17,False,1
4,0.0,0.477273,0.557377,0.390476,0.178571,0.200000,0.276081,0.674419,0.587302,0.753792,...,0.117949,0.243781,0.516129,PHI,0.440367,0.0,2018,2017-10-18,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.250000,0.360656,0.254762,0.357143,0.483333,0.287532,0.232558,0.269841,0.546091,...,0.157692,0.288557,0.322581,BOS,0.238532,1.0,2025,2025-04-13,False,2
20250,0.0,0.590909,0.409836,0.630952,0.571429,0.500000,0.469466,0.116279,0.142857,0.533256,...,0.148718,0.457711,0.559140,ORL,0.348624,0.0,2025,2025-04-13,True,2
20251,0.0,0.431818,0.409836,0.442857,0.500000,0.416667,0.474555,0.209302,0.222222,0.611435,...,0.134615,0.303483,0.430108,ATL,0.458716,1.0,2025,2025-04-13,False,2
20252,0.0,0.704545,0.672131,0.550000,0.500000,0.516667,0.394402,0.279070,0.222222,0.844807,...,0.124359,0.218905,0.645161,DAL,0.275229,0.0,2025,2025-04-13,True,2
20253,0.0,0.500000,0.344262,0.578571,0.357143,0.366667,0.366412,0.627907,0.492063,0.854142,...,0.132051,0.651741,0.580645,TOR,0.467890,0.0,2025,2025-04-13,True,2

In [39]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [40]:
predictors = list(selected_columns[sfs.get_support()])

In [41]:
predictors

['tov',
 'pf',
 'usg%',
 'ortg',
 'fta_max',
 '+/-_max',
 'ftr_max',
 'orb%_max',
 'stl%_max',
 'drtg_max',
 'fg_opp',
 'fg%_opp',
 '3pa_opp',
 '3p%_opp',
 'trb_opp',
 'ts%_opp',
 'stl%_opp',
 'blk%_opp',
 'usg%_opp',
 'drtg_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'ast_max_opp',
 'ts%_max_opp',
 'efg%_max_opp',
 'drb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'usg%_max_opp',
 'ortg_max_opp']

In [42]:
df.rename(columns={"seasons": "season"}, inplace=True)

C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\1178497399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"seasons": "season"}, inplace=True)

In [43]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    seasons = sorted(data["season"].unique())
    for i in range(start, len(seasons),step):
        season = seasons[i]
        train = data[data["season"] < season]
        test=data[data["season"] == season]
        model.fit(train[predictors], train["target"])
        preds = model.predict(test[predictors])#default numpyarray return
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [44]:
sorted(df["season"].unique())

[2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [45]:
predictions = backtest(df, rr, predictors)

In [46]:
predictions

       actual  prediction
5240        0           1
5241        0           0
5242        1           0
5243        1           1
5244        1           1
...       ...         ...
20249       2           0
20250       2           1
20251       2           1
20252       2           1
20253       2           1

[14996 rows x 2 columns]

In [47]:
from sklearn.metrics import accuracy_score
predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5513163169851664

In [48]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.438031
1.0    0.561969
dtype: float64

In [49]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [50]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.340909,0.409836,0.333333,0.250000,0.366667,0.246819,0.418605,0.380952,0.719953,...,0.060,0.283019,0.067949,0.194030,0.322581,0.321101,1.0,False,BOS,2018
1,0.0,0.386364,0.327869,0.450000,0.142857,0.200000,0.217557,0.465116,0.380952,0.813302,...,0.045,0.315514,0.101282,0.149254,0.376344,0.293578,0.0,True,CLE,2018
2,0.0,0.590909,0.557377,0.514286,0.500000,0.516667,0.394402,0.279070,0.285714,0.631272,...,0.091,0.284067,0.135897,0.751244,0.537634,0.495413,1.0,True,HOU,2018
3,0.0,0.500000,0.278689,0.640476,0.535714,0.333333,0.606870,0.418605,0.317460,0.889148,...,0.065,0.142558,0.117949,0.263682,0.526882,0.504587,0.0,False,GSW,2018
4,0.0,0.477273,0.557377,0.390476,0.178571,0.200000,0.276081,0.674419,0.587302,0.753792,...,0.044,0.192872,0.117949,0.243781,0.516129,0.440367,0.0,True,WAS,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.250000,0.360656,0.254762,0.357143,0.483333,0.287532,0.232558,0.269841,0.546091,...,0.140,0.371069,0.157692,0.288557,0.322581,0.238532,1.0,False,CHO,2025
20250,0.0,0.590909,0.409836,0.630952,0.571429,0.500000,0.469466,0.116279,0.142857,0.533256,...,0.158,0.283019,0.148718,0.457711,0.559140,0.348624,0.0,True,ATL,2025
20251,0.0,0.431818,0.409836,0.442857,0.500000,0.416667,0.474555,0.209302,0.222222,0.611435,...,0.095,0.323899,0.134615,0.303483,0.430108,0.458716,1.0,False,ORL,2025
20252,0.0,0.704545,0.672131,0.550000,0.500000,0.516667,0.394402,0.279070,0.222222,0.844807,...,0.109,0.222222,0.124359,0.218905,0.645161,0.275229,0.0,True,MEM,2025
20253,0.0,0.500000,0.344262,0.578571,0.357143,0.366667,0.366412,0.627907,0.492063,0.854142,...,0.025,0.149895,0.132051,0.651741,0.580645,0.467890,0.0,True,SAS,2025

In [51]:
def find_team_averages(team):
    numeric_cols = team.select_dtypes(include=["number"])  
    rolling = numeric_cols.rolling(10).mean() 
    return rolling

df_rolling = df.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [52]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,season,target
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.363636,0.367213,0.397857,0.342857,0.405000,0.323155,0.337209,0.312698,0.685648,...,0.0631,0.0940,0.328512,0.261154,0.459701,0.375269,0.449541,0.6,2025.0,0.3
20250,0.0,0.547727,0.447541,0.550476,0.517857,0.508333,0.413359,0.369767,0.328571,0.729638,...,0.0607,0.0913,0.310063,0.174872,0.439303,0.568817,0.477982,0.6,2025.0,0.7
20251,0.0,0.427273,0.368852,0.466429,0.428571,0.433333,0.381807,0.346512,0.303175,0.766511,...,0.1365,0.1054,0.384696,0.117436,0.421393,0.486022,0.315596,0.5,2025.0,0.8
20252,0.0,0.495455,0.465574,0.472381,0.496429,0.511667,0.399364,0.355814,0.311111,0.750525,...,0.0530,0.0696,0.245283,0.183333,0.370149,0.480645,0.464220,0.5,2025.0,0.6
20253,0.0,0.452273,0.406557,0.472143,0.485714,0.493333,0.397710,0.318605,0.288889,0.706651,...,0.0634,0.0769,0.389727,0.278333,0.537811,0.454839,0.479817,0.5,2025.0,0.5

In [53]:
rolling_cols= [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [54]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,season_10,target_10
0,0.0,0.340909,0.409836,0.333333,0.250000,0.366667,0.246819,0.418605,0.380952,0.719953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.386364,0.327869,0.450000,0.142857,0.200000,0.217557,0.465116,0.380952,0.813302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.590909,0.557377,0.514286,0.500000,0.516667,0.394402,0.279070,0.285714,0.631272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.500000,0.278689,0.640476,0.535714,0.333333,0.606870,0.418605,0.317460,0.889148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.477273,0.557377,0.390476,0.178571,0.200000,0.276081,0.674419,0.587302,0.753792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.250000,0.360656,0.254762,0.357143,0.483333,0.287532,0.232558,0.269841,0.546091,...,0.0631,0.0940,0.328512,0.261154,0.459701,0.375269,0.449541,0.6,2025.0,0.3
20250,0.0,0.590909,0.409836,0.630952,0.571429,0.500000,0.469466,0.116279,0.142857,0.533256,...,0.0607,0.0913,0.310063,0.174872,0.439303,0.568817,0.477982,0.6,2025.0,0.7
20251,0.0,0.431818,0.409836,0.442857,0.500000,0.416667,0.474555,0.209302,0.222222,0.611435,...,0.1365,0.1054,0.384696,0.117436,0.421393,0.486022,0.315596,0.5,2025.0,0.8
20252,0.0,0.704545,0.672131,0.550000,0.500000,0.516667,0.394402,0.279070,0.222222,0.844807,...,0.0530,0.0696,0.245283,0.183333,0.370149,0.480645,0.464220,0.5,2025.0,0.6
20253,0.0,0.500000,0.344262,0.578571,0.357143,0.366667,0.366412,0.627907,0.492063,0.854142,...,0.0634,0.0769,0.389727,0.278333,0.537811,0.454839,0.479817,0.5,2025.0,0.5

In [55]:
df = df.dropna()

In [56]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,season_10,target_10
256,0.0,0.295455,0.409836,0.278571,0.285714,0.400000,0.265903,0.372093,0.333333,0.735123,...,0.0594,0.1126,0.388889,0.192436,0.381592,0.364516,0.370642,0.4,2018.0,0.1
259,0.0,0.477273,0.426230,0.483333,0.535714,0.616667,0.361323,0.418605,0.349206,0.796966,...,0.0593,0.1114,0.327883,0.131667,0.336816,0.438710,0.326606,0.7,2018.0,0.7
261,0.0,0.431818,0.393443,0.454762,0.321429,0.283333,0.399491,0.186047,0.174603,0.708285,...,0.0586,0.1045,0.388155,0.189487,0.343781,0.350538,0.366055,0.5,2018.0,0.2
264,0.0,0.431818,0.262295,0.564286,0.428571,0.233333,0.618321,0.325581,0.333333,0.628938,...,0.0529,0.0751,0.429245,0.164231,0.322388,0.440860,0.313761,0.5,2018.0,0.7
265,0.0,0.431818,0.393443,0.454762,0.178571,0.233333,0.246819,0.488372,0.412698,0.784131,...,0.0512,0.1056,0.350105,0.159487,0.437313,0.427957,0.360550,0.5,2018.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.250000,0.360656,0.254762,0.357143,0.483333,0.287532,0.232558,0.269841,0.546091,...,0.0631,0.0940,0.328512,0.261154,0.459701,0.375269,0.449541,0.6,2025.0,0.3
20250,0.0,0.590909,0.409836,0.630952,0.571429,0.500000,0.469466,0.116279,0.142857,0.533256,...,0.0607,0.0913,0.310063,0.174872,0.439303,0.568817,0.477982,0.6,2025.0,0.7
20251,0.0,0.431818,0.409836,0.442857,0.500000,0.416667,0.474555,0.209302,0.222222,0.611435,...,0.1365,0.1054,0.384696,0.117436,0.421393,0.486022,0.315596,0.5,2025.0,0.8
20252,0.0,0.704545,0.672131,0.550000,0.500000,0.516667,0.394402,0.279070,0.222222,0.844807,...,0.0530,0.0696,0.245283,0.183333,0.370149,0.480645,0.464220,0.5,2025.0,0.6
20253,0.0,0.500000,0.344262,0.578571,0.357143,0.366667,0.366412,0.627907,0.492063,0.854142,...,0.0634,0.0769,0.389727,0.278333,0.537811,0.454839,0.479817,0.5,2025.0,0.5

In [57]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col
def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x:shift_col(x,col_name))
df["home_next"] = add_col(df, "home") #next game
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\4130912735.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home") #next game
C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\4130912735.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
C:\Users\tahsi\AppData\Local\Temp\ipykernel_33832\4130912735.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [58]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,season_10,target_10,home_next,team_opp_next,date_next
256,0.0,0.295455,0.409836,0.278571,0.285714,0.400000,0.265903,0.372093,0.333333,0.735123,...,0.192436,0.381592,0.364516,0.370642,0.4,2018.0,0.1,0.0,MIN,2017-11-04
259,0.0,0.477273,0.426230,0.483333,0.535714,0.616667,0.361323,0.418605,0.349206,0.796966,...,0.131667,0.336816,0.438710,0.326606,0.7,2018.0,0.7,1.0,UTA,2017-11-05
261,0.0,0.431818,0.393443,0.454762,0.321429,0.283333,0.399491,0.186047,0.174603,0.708285,...,0.189487,0.343781,0.350538,0.366055,0.5,2018.0,0.2,0.0,WAS,2017-11-07
264,0.0,0.431818,0.262295,0.564286,0.428571,0.233333,0.618321,0.325581,0.333333,0.628938,...,0.164231,0.322388,0.440860,0.313761,0.5,2018.0,0.7,1.0,IND,2017-11-08
265,0.0,0.431818,0.393443,0.454762,0.178571,0.233333,0.246819,0.488372,0.412698,0.784131,...,0.159487,0.437313,0.427957,0.360550,0.5,2018.0,0.6,1.0,BRK,2017-11-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,0.0,0.250000,0.360656,0.254762,0.357143,0.483333,0.287532,0.232558,0.269841,0.546091,...,0.261154,0.459701,0.375269,0.449541,0.6,2025.0,0.3,NaN,None,None
20250,0.0,0.590909,0.409836,0.630952,0.571429,0.500000,0.469466,0.116279,0.142857,0.533256,...,0.174872,0.439303,0.568817,0.477982,0.6,2025.0,0.7,NaN,None,None
20251,0.0,0.431818,0.409836,0.442857,0.500000,0.416667,0.474555,0.209302,0.222222,0.611435,...,0.117436,0.421393,0.486022,0.315596,0.5,2025.0,0.8,NaN,None,None
20252,0.0,0.704545,0.672131,0.550000,0.500000,0.516667,0.394402,0.279070,0.222222,0.844807,...,0.183333,0.370149,0.480645,0.464220,0.5,2025.0,0.6,NaN,None,None
20253,0.0,0.500000,0.344262,0.578571,0.357143,0.366667,0.366412,0.627907,0.492063,0.854142,...,0.278333,0.537811,0.454839,0.479817,0.5,2025.0,0.5,NaN,None,None

In [59]:
df = df.copy()

In [60]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"], 
    right_on=["team_opp_next", "date_next"]
)

In [61]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,season_10_y,target_10_y,team_opp_next_y,team_y
0,0.00,0.431818,0.262295,0.564286,0.428571,0.233333,0.618321,0.325581,0.333333,0.628938,...,0.286688,0.164872,0.421891,0.437634,0.373394,0.6,2018.0,0.4,DET,IND
1,0.00,0.431818,0.393443,0.454762,0.178571,0.233333,0.246819,0.488372,0.412698,0.784131,...,0.385849,0.137564,0.314925,0.407527,0.455046,0.5,2018.0,0.4,DEN,BRK
2,0.25,0.318182,0.393443,0.316667,0.285714,0.350000,0.297710,0.372093,0.333333,0.735123,...,0.291090,0.160513,0.415920,0.443011,0.386239,0.6,2018.0,0.4,NOP,IND
3,0.00,0.363636,0.180328,0.550000,0.214286,0.166667,0.374046,0.488372,0.428571,0.750292,...,0.380608,0.235769,0.323881,0.400000,0.285321,0.4,2018.0,0.6,POR,MEM
4,0.00,0.272727,0.459016,0.223810,0.178571,0.316667,0.192112,0.348837,0.269841,0.870478,...,0.547799,0.201282,0.346269,0.446237,0.355046,0.3,2018.0,0.6,ORL,NYK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17957,0.00,0.568182,0.491803,0.538095,0.607143,0.483333,0.516539,0.186047,0.269841,0.416569,...,0.285535,0.153590,0.370647,0.540860,0.466972,0.5,2025.0,0.8,DET,MIL
17958,0.00,0.636364,0.360656,0.730952,0.428571,0.366667,0.445293,0.395349,0.317460,0.833139,...,0.303145,0.170385,0.425871,0.559140,0.492661,0.7,2025.0,0.5,ORL,ATL
17959,0.00,0.431818,0.426230,0.428571,0.392857,0.316667,0.455471,0.511628,0.539683,0.599767,...,0.269916,0.118974,0.293035,0.558065,0.439450,0.5,2025.0,0.6,IND,CLE
17960,0.00,0.454545,0.442623,0.445238,0.607143,0.683333,0.377863,0.186047,0.174603,0.708285,...,0.292872,0.237949,0.378607,0.527957,0.459633,0.3,2025.0,0.5,HOU,DEN
17961,0.00,0.522727,0.459016,0.511905,0.142857,0.233333,0.193384,0.534884,0.476190,0.736289,...,0.488784,0.218462,0.417910,0.565591,0.430275,0.6,2025.0,0.6,DEN,HOU

In [62]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        DET             IND    IND             DET  2017-11-08
1        DEN             BRK    BRK             DEN  2017-11-07
2        NOP             IND    IND             NOP  2017-11-07
3        POR             MEM    MEM             POR  2017-11-07
4        ORL             NYK    NYK             ORL  2017-11-08
...      ...             ...    ...             ...         ...
17957    DET             MIL    MIL             DET  2025-04-13
17958    ORL             ATL    ATL             ORL  2025-04-13
17959    IND             CLE    CLE             IND  2025-04-13
17960    HOU             DEN    DEN             HOU  2025-04-13
17961    DEN             HOU    HOU             DEN  2025-04-13

[17962 rows x 5 columns]

In [63]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [64]:
#full.columns[full.dtypes == "object"]

In [65]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'seasons',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [66]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [67]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [68]:
predictors = list(selected_columns[sfs.get_support()])

In [69]:
predictors

['blk',
 'blk%',
 'tov%',
 'usg%',
 'blk%_max',
 'ortg_max',
 'ts%_opp',
 'usg%_opp',
 'usg%_max_opp',
 'ortg_max_opp',
 'drtg_max_opp',
 '3p%_10_x',
 'usg%_10_x',
 'drb_max_10_x',
 'pts_max_10_x',
 '+/-_max_10_x',
 'usg%_max_10_x',
 'ts%_opp_10_x',
 'usg%_opp_10_x',
 'blk_max_opp_10_x',
 '+/-_max_opp_10_x',
 'target_10_x',
 'home_next',
 'usg%_10_y',
 '+/-_max_10_y',
 'ast%_max_10_y',
 '3p_opp_10_y',
 'usg%_opp_10_y',
 '+/-_max_opp_10_y',
 'target_10_y']

In [70]:
predictions = backtest(full, rr, predictors)

In [71]:
accuracy_score(predictions["actual"],predictions["prediction"])

0.7817155756207675

In [72]:
#how to continue to improve accuracy
#try using more powerful than ridge regression model like random forest classifier
#try out different numbers of features you're selecting for the model (like last 15 games or last 20 games or last 5 games)

In [73]:
#for future get most up to date data 
#fill in home_next, team_opp_next, date_next
#rerun 
#look at any rows with target value 2, find predictions based on that